spring:
  datasource:
    url: jdbc:postgresql://localhost:${local.db.port:5432}/postgres
    username: postgres
    password: ""
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true

local:
  db:
    port: 15432

logging:
  level:
    com.dodognoman.rungame: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
